### ISSUE TITLE
Support pixel flipping in drawing functions

### ISSUE THREAD

**Issue by fuglaro** [Timendus/thumby-grayscale#23]
If this get's merged.
https://github.com/TinyCircuits/TinyCircuits-Thumby-Code-Editor/pull/71

**Comment by Xyvir** [comment]
This can be closed, the suggestion was not merged into the main thumby API:

https://github.com/TinyCircuits/TinyCircuits-Thumby-Code-Editor/pull/72

**Comment by Xyvir** [comment]
@fuglaro
