### ISSUE TITLE
New thumby doesn't work with the grayscale library

### ISSUE THREAD

**Issue by EtherealZenith** [Timendus/thumby-grayscale#24]
I got a thumby a couple weeks ago and when using the grayscale library, the image either flickers between two positions, or is just monochrome. It gives different results randomly, so I think it's a timing issue.

**Comment by EtherealZenith** [comment]
I see, this is the same issue as here: https://github.com/Timendus/thumby-grayscale/issues/12
Using this fix posted in that thread (https://gist.github.com/AngelJA/7076a0ff19912fc06b2cffff23563d7f) I got it to work.
My fix was just copying the grayscale calibration code on that page, and then removing the extra "calibration code" at the end, so there may be leftover excess code with my fix, but it does work.

**Comment by fuglaro** [comment]
Thank you for reporting this and testing that fix! I'm hoping my new
Thumby's arrive soon so I can incorporate that fix into something that
works for all Thumby's.

**Comment by fuglaro** [comment]
Hi! I believe this should be fixed as of v4.0.2.
